name: bank-marketing-karim
services:
  spark-master:
    build: .
    image: bank-spark
    hostname: spark-master
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    volumes: 
      - type: bind
        source: ./simple_dataframe.py
        target: /opt/spark/code/simple_dataframe.py
        bind: 
          create_host_path: false
      - type: bind
        source: ./bank_master.csv
        target: /opt/spark/data/bank_master.csv
        bind: 
          create_host_path: false
    command: /opt/spark/sbin/start-master.sh 
    ports:
      - 8080:8080
    environment:
      - SPARK_NO_DAEMONIZE=1

  worker1:
    hostname: worker1
    build: .
    image: bank-spark
    depends_on:
      - spark-master
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1000M
    volumes:
      - type: bind
        source: ./bank_worker1.csv
        target: /opt/spark/data/bank_worker1.csv
        bind:
          create_host_path: false
    environment:
      - SPARK_NO_DAEMONIZE=1
    command: /opt/spark/sbin/start-worker.sh spark://spark-master:7077

  worker2:
    hostname: worker2
    build: .
    image: bank-spark
    depends_on:
      - spark-master
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1000M
    volumes:
      - type: bind
        source: ./bank_worker2.csv
        target: /opt/spark/data/bank_worker2.csv
        bind:
          create_host_path: false
    environment:
      - SPARK_NO_DAEMONIZE=1
    command: /opt/spark/sbin/start-worker.sh spark://spark-master:7077